### ISSUE TITLE
mesh2sdf errors

### ISSUE THREAD

**Issue by kingcodefish** [nv-tlabs/nglod#20]
Hi,

I'm trying to build the sdf-net portion of the repository, but I'm having issues with the mesh2sdf library. I'm not entirely sure what library this corresponds to because it's not in the requirements.txt, but I've guessed that it must be the [mesh-to-sdf](https://github.com/marian42/mesh_to_sdf) library. I've tried this and changing the imports to match, but the build still breaks in [compute_sdf.py](https://github.com/nv-tlabs/nglod/blob/4d1110eb454394ebd527618887f35e59d624a402/sdf-net/lib/torchgp/compute_sdf.py). which uses mesh2sdf_gpu and doesn't exist in mesh-to-sdf.

So I'm curious what library I'm supposed to use for this or if this is just legacy code that needs to be reconfigured. I've had other dependency issues, but so far, those have been pretty easy to resolve. Happy to help contribute for this, but want to make sure I'm not making a glaring mistake.

Thanks.

**Comment by joeylitalien** [comment]
Hi @kingcodefish,

Our codebase relies on two custom CUDA kernels which can be found in `sdf-net/lib/extensions`, where `mesh2sdf` is one of them. You can refer to our [read-me file](https://github.com/nv-tlabs/nglod#building-cuda-extensions) for install instructions. What other dependency issues were you having?

**Comment by kingcodefish** [comment]
@joeylitalien Whoops, my bad. Somehow I managed to skip over that part of the setup. I've now built the extensions and have gotten the neural network to train on the armadillo example. However, when I run the following command to export the .npz file:
```
python app/sdf_renderer.py \
    --net OctreeSDF \
    --num-lods 5 \
    --pretrained _results/models/armadillo.pth \
    --render-res 1280 720 \
    --shading-mode matcap \
    --lod 4
    --export armadillo.npz
```
I get the following error:
```
Total number of parameters: 10146213
Traceback (most recent call last):
  File "app/sdf_renderer.py, line 106, in <module>
    net = SOL_NGLOD(net)
  File "~/Documents/nglod/sdf-net/lib/models/SOL_NGLOD.py", line 50, in __init__
    self.vs = voxel_sparsify(2000000, net, self.lod, sol=False)
  File "~/Documents/nglod/sdf-net/lib/renderutils.py", line 63, in voxel_sparsify
    surface = sample_surface(n, net, sol=sol, device=device)[:n]
  File "~/Documents/nglod/sdf-net/lib/renderutils.py", line 33, in sample_surface
    tracer = SphereTracer(device, sol=sol)
TypeError: __init__() got an unexpected keyword argument 'sol'
```

**Comment by tovacinni** [comment]
A lot of this is affected by some recent refactors we've had which includes deprecating some of the exporting capabilities to opt for a Python-based interactive renderer. Said Python-based renderer isn't available yet but will be soon (hopefully over the weekend)!

**Comment by zhaoyuanyuan2011** [comment]
> @joeylitalien Whoops, my bad. Somehow I managed to skip over that part of the setup. I've now built the extensions and have gotten the neural network to train on the armadillo example. However, when I run the following command to export the .npz file:
> 
> ```
> python app/sdf_renderer.py \
>     --net OctreeSDF \
>     --num-lods 5 \
>     --pretrained _results/models/armadillo.pth \
>     --render-res 1280 720 \
>     --shading-mode matcap \
>     --lod 4
>     --export armadillo.npz
> ```
> 
> I get the following error:
> 
> ```
> Total number of parameters: 10146213
> Traceback (most recent call last):
>   File "app/sdf_renderer.py, line 106, in <module>
>     net = SOL_NGLOD(net)
>   File "~/Documents/nglod/sdf-net/lib/models/SOL_NGLOD.py", line 50, in __init__
>     self.vs = voxel_sparsify(2000000, net, self.lod, sol=False)
>   File "~/Documents/nglod/sdf-net/lib/renderutils.py", line 63, in voxel_sparsify
>     surface = sample_surface(n, net, sol=sol, device=device)[:n]
>   File "~/Documents/nglod/sdf-net/lib/renderutils.py", line 33, in sample_surface
>     tracer = SphereTracer(device, sol=sol)
> TypeError: __init__() got an unexpected keyword argument 'sol'
> ```

Hi @kingcodefish  I'm just wondering have you solved the `TypeError: __init__() got an unexpected keyword argument 'sol'` issue? Thank you!

**Comment by Sylva-Lin** [comment]
> @joeylitalien Whoops, my bad. Somehow I managed to skip over that part of the setup. I've now built the extensions and have gotten the neural network to train on the armadillo example. However, when I run the following command to export the .npz file:
> 
> ```
> python app/sdf_renderer.py \
>     --net OctreeSDF \
>     --num-lods 5 \
>     --pretrained _results/models/armadillo.pth \
>     --render-res 1280 720 \
>     --shading-mode matcap \
>     --lod 4
>     --export armadillo.npz
> ```
> 
> I get the following error:
> 
> ```
> Total number of parameters: 10146213
> Traceback (most recent call last):
>   File "app/sdf_renderer.py, line 106, in <module>
>     net = SOL_NGLOD(net)
>   File "~/Documents/nglod/sdf-net/lib/models/SOL_NGLOD.py", line 50, in __init__
>     self.vs = voxel_sparsify(2000000, net, self.lod, sol=False)
>   File "~/Documents/nglod/sdf-net/lib/renderutils.py", line 63, in voxel_sparsify
>     surface = sample_surface(n, net, sol=sol, device=device)[:n]
>   File "~/Documents/nglod/sdf-net/lib/renderutils.py", line 33, in sample_surface
>     tracer = SphereTracer(device, sol=sol)
> TypeError: __init__() got an unexpected keyword argument 'sol'
> ```

how did you solve this problem( TypeError: __init__() got an unexpected keyword argument 'sol') in the end？Thank you!
