### ISSUE TITLE
Can't export .npz files

### ISSUE THREAD

**Issue by lccatala** [nv-tlabs/nglod#33]
Hi, when running the example command in the README for rendering, along with the --export flag (`python app/sdf_renderer.py \
    --net OctreeSDF \
    --num-lods 5 \
    --pretrained _results/models/armadillo.pth \
    --render-res 1280 720 \
    --shading-mode matcap \
    --lod 4 --export file.npz`

I get the following error message
`Total number of parameters: 10146213
Traceback (most recent call last):
  File "app/sdf_renderer.py", line 106, in <module>
    net = SOL_NGLOD(net)
  File "/home/luis/nglod/sdf-net/lib/models/SOL_NGLOD.py", line 50, in __init__
    self.vs = voxel_sparsify(2000000, net, self.lod, sol=False)
  File "/home/luis/nglod/sdf-net/lib/renderutils.py", line 63, in voxel_sparsify
    surface = sample_surface(n, net, sol=sol, device=device)[:n]
  File "/home/luis/nglod/sdf-net/lib/renderutils.py", line 33, in sample_surface
    tracer = SphereTracer(device, sol=sol)
TypeError: __init__() got an unexpected keyword argument 'sol'`

I cannot figure out how to fix it.

Thank you in advance

**Comment by Sylva-Lin** [comment]
I also had the same problem, did you solve it?

**Comment by nickbroeks** [comment]
If this problem occurs for anyone else in the future. The problem seems to be commit https://github.com/nv-tlabs/nglod/commit/ef1c08a466b2db02003afdcd0259d0add6c9eb26
