### ISSUE TITLE
Building CUDA extensions failed

### ISSUE THREAD

**Issue by Quantuman134** [nv-tlabs/nglod#40]
The building process was not completed when I runned the command
```
chmod +x build_ext.sh && ./build_ext.sh
```
The error was rised:
```
TypeError: expected string or bytes-like object
./build_ext.sh: line 3: cd: sol_nglod: No such file or directory
```

the entire information is as follows

```
No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda-12.0'
running clean
'build/lib.linux-x86_64-cpython-38' does not exist -- can't clean it
'build/bdist.linux-x86_64' does not exist -- can't clean it
'build/scripts-3.8' does not exist -- can't clean it
running install
/home/quantum/anaconda3/envs/nglod/lib/python3.8/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
/home/quantum/anaconda3/envs/nglod/lib/python3.8/site-packages/setuptools/command/easy_install.py:144: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
running bdist_egg
running egg_info
writing mesh2sdf.egg-info/PKG-INFO
writing dependency_links to mesh2sdf.egg-info/dependency_links.txt
writing top-level names to mesh2sdf.egg-info/top_level.txt
reading manifest file 'mesh2sdf.egg-info/SOURCES.txt'
adding license file 'NOTICE'
writing manifest file 'mesh2sdf.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_ext
Traceback (most recent call last):
  File "setup.py", line 13, in <module>
    setup(
  File "/home/quantum/anaconda3/envs/nglod/lib/python3.8/site-packages/setuptools/__init__.py", line 87, in setup
    return distutils.core.setup(**attrs)
  File "/home/quantum/anaconda3/envs/nglod/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 185, in setup
    return run_commands(dist)
  File "/home/quantum/anaconda3/envs/nglod/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
    dist.run_commands()
  File "/home/quantum/anaconda3/envs/nglod/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
    self.run_command(cmd)
  File "/home/quantum/anaconda3/envs/nglod/lib/python3.8/site-packages/setuptools/dist.py", line 1208, in run_command
    super().run_command(command)
  File "/home/quantum/anaconda3/envs/nglod/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/home/quantum/anaconda3/envs/nglod/lib/python3.8/site-packages/setuptools/command/install.py", line 74, in run
    self.do_egg_install()
  File "/home/quantum/anaconda3/envs/nglod/lib/python3.8/site-packages/setuptools/command/install.py", line 123, in do_egg_install
    self.run_command('bdist_egg')
  File "/home/quantum/anaconda3/envs/nglod/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
    self.distribution.run_command(command)
  File "/home/quantum/anaconda3/envs/nglod/lib/python3.8/site-packages/setuptools/dist.py", line 1208, in run_command
    super().run_command(command)
  File "/home/quantum/anaconda3/envs/nglod/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/home/quantum/anaconda3/envs/nglod/lib/python3.8/site-packages/setuptools/command/bdist_egg.py", line 165, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "/home/quantum/anaconda3/envs/nglod/lib/python3.8/site-packages/setuptools/command/bdist_egg.py", line 151, in call_command
    self.run_command(cmdname)
  File "/home/quantum/anaconda3/envs/nglod/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
    self.distribution.run_command(command)
  File "/home/quantum/anaconda3/envs/nglod/lib/python3.8/site-packages/setuptools/dist.py", line 1208, in run_command
    super().run_command(command)
  File "/home/quantum/anaconda3/envs/nglod/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/home/quantum/anaconda3/envs/nglod/lib/python3.8/site-packages/setuptools/command/install_lib.py", line 11, in run
    self.build()
  File "/home/quantum/anaconda3/envs/nglod/lib/python3.8/site-packages/setuptools/_distutils/command/install_lib.py", line 112, in build
    self.run_command('build_ext')
  File "/home/quantum/anaconda3/envs/nglod/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
    self.distribution.run_command(command)
  File "/home/quantum/anaconda3/envs/nglod/lib/python3.8/site-packages/setuptools/dist.py", line 1208, in run_command
    super().run_command(command)
  File "/home/quantum/anaconda3/envs/nglod/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/home/quantum/anaconda3/envs/nglod/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 84, in run
    _build_ext.run(self)
  File "/home/quantum/anaconda3/envs/nglod/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 346, in run
    self.build_extensions()
  File "/home/quantum/anaconda3/envs/nglod/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 436, in build_extensions
    self._check_cuda_version(compiler_name, compiler_version)
  File "/home/quantum/anaconda3/envs/nglod/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 813, in _check_cuda_version
    torch_cuda_version = packaging.version.parse(torch.version.cuda)
  File "/home/quantum/anaconda3/envs/nglod/lib/python3.8/site-packages/pkg_resources/_vendor/packaging/version.py", line 49, in parse
    return Version(version)
  File "/home/quantum/anaconda3/envs/nglod/lib/python3.8/site-packages/pkg_resources/_vendor/packaging/version.py", line 264, in __init__
    match = self._regex.search(version)
TypeError: expected string or bytes-like object
./build_ext.sh: line 3: cd: sol_nglod: No such file or directory

```

**Comment by AXuanCreator** [comment]
Hi,
I had the same problem as you and would like to know how you solved it : )
